const blogData = [
  {
    id: 1,
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    header: 'Understanding Your Weekly Horoscope',
    text: 'Discover how the planets influence your mood, decisions, and fate in this week’s horoscope breakdown.',
    category: 'Horoscope',
    author: 'Admin',
    likes: 1244,
    comments: 256,
    date: '2025-08-28',
    tags: ['News', 'Horoscope'],
  },
  {
    id: 2,
    url: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=80',
    header: '5 Ways to Find Inner Peace Through Meditation',
    text: 'Learn effective meditation techniques to help calm your mind and improve your overall wellbeing.',
    category: 'Wellness',
    author: 'Admin',
    likes: 874,
    comments: 145,
    date: '2025-08-25',
    tags: ['Wellness', 'Spiritual'],
  },
  {
    id: 3,
    url: 'https://images.unsplash.com/photo-1549887534-627fc3e9e1c9?auto=format&fit=crop&w=800&q=80',
    header: 'Zodiac Signs Ranked by Intelligence',
    text: 'Do zodiac signs affect intelligence? We take a lighthearted look at the stars and brains.',
    category: 'Zodiac',
    author: 'Admin',
    likes: 1322,
    comments: 312,
    date: '2025-08-30',
    tags: ['Fun', 'Astrology'],
  },
  {
    id: 4,
    url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
    header: 'How the Full Moon Affects Your Emotions',
    text: 'Many believe that the moon cycles impact our emotions and energy. Let’s explore the science and myths.',
    category: 'Science',
    author: 'Admin',
    likes: 653,
    comments: 88,
    date: '2025-08-21',
    tags: ['Lunar', 'Health'],
  },
  {
    id: 5,
    url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    header: 'Morning Yoga Routines to Start Your Day Right',
    text: 'Improve your focus, flexibility, and peace of mind with these energizing morning yoga flows.',
    category: 'Fitness',
    author: 'Admin',
    likes: 987,
    comments: 165,
    date: '2025-08-20',
    tags: ['Fitness', 'Routine'],
  },
  {
    id: 6,
    url: 'https://images.unsplash.com/photo-1509228627152-2132efb1d240?auto=format&fit=crop&w=800&q=80',
    header: 'Crystal Healing: What You Need to Know',
    text: 'Curious about crystal healing? Here’s a beginner’s guide to popular stones and how they’re used.',
    category: 'Healing',
    author: 'Admin',
    likes: 541,
    comments: 72,
    date: '2025-08-18',
    tags: ['Healing', 'Crystals'],
  },
  {
    id: 7,
    url: 'https://images.unsplash.com/photo-1549122728-f519709caa9c?auto=format&fit=crop&w=800&q=80',
    header: 'A Beginner’s Guide to Reading Tarot Cards',
    text: 'Step into the mystical world of tarot and learn the meanings behind popular cards and spreads.',
    category: 'Spirituality',
    author: 'Admin',
    likes: 1203,
    comments: 211,
    date: '2025-08-15',
    tags: ['Tarot', 'Spirituality'],
  },
  {
    id: 8,
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    header: 'The Astrology of 2025: Big Shifts Ahead',
    text: '2025 brings major planetary shifts. Here’s what to expect for each zodiac sign.',
    category: 'Forecast',
    author: 'Admin',
    likes: 1001,
    comments: 194,
    date: '2025-08-10',
    tags: ['Forecast', 'Zodiac'],
  },
  {
    id: 9,
    url: 'https://images.unsplash.com/photo-1486308510493-cb52c3cf89a7?auto=format&fit=crop&w=800&q=80',
    header: 'The Power of Journaling for Mental Clarity',
    text: 'Explore how daily journaling can reduce stress, boost creativity, and bring emotional balance.',
    category: 'Mindfulness',
    author: 'Admin',
    likes: 712,
    comments: 134,
    date: '2025-08-05',
    tags: ['Mindfulness', 'Mental Health'],
  },
  {
    id: 10,
    url: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80',
    header: 'Daily Affirmations to Boost Your Vibration',
    text: 'Positive affirmations can reset your mindset. Try these daily mantras for a better you.',
    category: 'Affirmations',
    author: 'Admin',
    likes: 898,
    comments: 176,
    date: '2025-08-01',
    tags: ['Affirmations', 'Positivity'],
  },

  // 📚 New Book-Related Blogs
  {
    id: 11,
    url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    header: 'Top 10 Must-Read Spiritual Books of 2025',
    text: 'From ancient wisdom to modern mindfulness, these books are reshaping the spiritual journey.',
    category: 'Books',
    author: 'Editor',
    likes: 1033,
    comments: 210,
    date: '2025-08-27',
    tags: ['Books', 'Spiritual'],
  },
  {
    id: 12,
    url: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=800&q=80',
    header: 'Why Reading Fiction Can Be Healing',
    text: 'Escape into another world and find yourself. Discover how stories can restore your mental health.',
    category: 'Books',
    author: 'Editor',
    likes: 874,
    comments: 133,
    date: '2025-08-22',
    tags: ['Books', 'Healing'],
  },
  {
    id: 13,
    url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=800&q=80',
    header: 'Reading Routines That Boost Productivity',
    text: 'Here’s how successful people structure their reading habits to spark creativity and productivity.',
    category: 'Books',
    author: 'Editor',
    likes: 982,
    comments: 122,
    date: '2025-08-19',
    tags: ['Books', 'Productivity'],
  },
  {
    id: 14,
    url: 'https://images.unsplash.com/photo-1510936111840-65e151ad71bb?auto=format&fit=crop&w=800&q=80',
    header: 'How to Build a Personal Library You Love',
    text: 'Curate your own space of knowledge, imagination, and comfort with these book organization tips.',
    category: 'Lifestyle',
    author: 'Admin',
    likes: 763,
    comments: 101,
    date: '2025-08-14',
    tags: ['Books', 'Lifestyle'],
  },
  {
    id: 15,
    url: 'https://images.unsplash.com/photo-1531219432768-9f540ce91ef8?auto=format&fit=crop&w=800&q=80',
    header: 'Ebooks vs Physical Books: What’s Best for You?',
    text: 'Convenience or tradition? Let’s break down the pros and cons of digital vs print reading experiences.',
    category: 'Books',
    author: 'Editor',
    likes: 845,
    comments: 98,
    date: '2025-08-08',
    tags: ['Books', 'Technology'],
  }
];

export default blogData;
